import { IBM_Plex_Sans_Thai, IBM_Plex_Sans_Thai_Looped } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next"
import "./globals.css";

import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import Particles from "../components/Particles";


const ibmPlexSansThai = IBM_Plex_Sans_Thai({
  weight: ["400"],
  variable: "--font-geist-sans",
  subsets: ["thai"],
});

const ibmPlexSansThaiLooped = IBM_Plex_Sans_Thai_Looped({
  weight: ["400"],
  variable: "--font-geist-mono",
  subsets: ["thai"],
});

export const metadata = {
  title: "Patcharadol | Portfolio",
  description: "Generated by create next app",
  icons: { shortcut: "/PortLogoWhite.svg" },
};



export default function RootLayout({ children }) {


  return (
    <html lang='en'>
      <body
        className={`${ibmPlexSansThai.variable} ${ibmPlexSansThaiLooped.variable} antialiased`}
      >
        
        <NavBar />
        <img src="/PortLogoWhite.svg" alt="Logo" className='flex fixed mt-5 opacity-80 h-12 w-12 right-5 md:left-10 z-90' />
        <div style={{ width: '100%', height: '100%', position: 'fixed', zIndex: -1 }} >
          <Particles
            particleColors={['#ffffff', '#ffffff']}
            particleCount={200}
            particleSpread={10}
            speed={0.1}
            particleBaseSize={20}
            moveParticlesOnHover={true}
            alphaParticles={false}
            disableRotation={false}
          />
        </div>

        {children}
        <SpeedInsights />
        <Footer />

      </body>
    </html>
  );
}
